python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Allensville_for_rrt/mesh_z_up.obj' --height=0.47 --num_nodes=5000
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Uvalda_for_rrt/mesh_z_up.obj' --height=0.681 --num_nodes=9284
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Darden_for_rrt/mesh_z_up.obj' --height=3.40 --num_nodes=6144
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Collierville_for_rrt/mesh_z_up.obj' --height=0.46 --num_nodes=2761
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Cosmos_for_rrt/mesh_z_up.obj' --height=0.65 --num_nodes=8090
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Forkland_for_rrt/mesh_z_up.obj' --height=0.35 --num_nodes=5011
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Hanson_for_rrt/mesh_z_up.obj' --height=0.35 --num_nodes=6017
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Hiteman_for_rrt/mesh_z_up.obj' --height=0.40 --num_nodes=4508
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Klickitat_for_rrt/mesh_z_up.obj' --height=0.40 --num_nodes=22138
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Lakeville_for_rrt/mesh_z_up.obj' --height=0.50 --num_nodes=18224
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Tolstoy_for_rrt/mesh_z_up.obj' --height=3.50 --num_nodes=10931
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Wainscott_for_rrt/mesh_z_up.obj' --height=1.0 --num_nodes=13684
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/McDade_for_rrt/mesh_z_up.obj' --height=3.16 --num_nodes=12870
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Mifflinburg_for_rrt/mesh_z_up.obj' --height=0.417 --num_nodes=3981
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Muleshoe_for_rrt/mesh_z_up.obj' --height=1.9 --num_nodes=22908
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Newfields_for_rrt/mesh_z_up.obj' --height=0.492 --num_nodes=8573
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Noxapater_for_rrt/mesh_z_up.obj' --height=0.523 --num_nodes=760
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Onaga_for_rrt/mesh_z_up.obj' --height=0.46 --num_nodes=4192
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Pinesdale_for_rrt/mesh_z_up.obj' --height=0.406 --num_nodes=14405
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Pomaria_for_rrt/mesh_z_up.obj' --height=0.492 --num_nodes=9260
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Shelbyville_for_rrt/mesh_z_up.obj' --height=0.691 --num_nodes=9568
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Stockman_for_rrt/mesh_z_up.obj' --height=3.30 --num_nodes=7167
python make_rrt.py --mesh_name='/home/reza/Datasets/GibsonEnv/gibson/assets/dataset/Wiconisco_for_rrt/mesh_z_up.obj' --height=0.517 --num_nodes=9973
